## 1使用numpy构建基本函数
### 1.1 sigmoid函数和np.exp()

In [1]:
import numpy as np
x = np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [2]:
# 使用np.exp构建sigmoid函数
def sigmoid(x):
    s = 1/(1+np.exp(-x))
    return s

print(sigmoid(x))

[0.73105858 0.88079708 0.95257413]


### 1.2 Sigmoid gradient

In [3]:
def sigmoid_gradient(x):
    s = 1/(1+np.exp(-x))
    ds = s * (1-s)
    return ds

In [4]:
print(sigmoid_gradient(x))

[0.19661193 0.10499359 0.04517666]


### 1.3 重塑数组

In [5]:
def reshape(array):
    v = array.reshape(array.shape[0]*array.shape[1]*array.shape[2],1)
    return v

In [6]:
array_1 = np.zeros((3,4,2))
print(array_1)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [7]:
print(reshape(array_1))

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### 1.4 行标准化

In [8]:
def normalizeRows(x):
    # 按照行求范数
    x_norm = np.linalg.norm(x,axis=1,keepdims=True)
    # 标准化
    x = x/x_norm
    return x

In [9]:
 x = np.array([[1,2,3],[4,5,6]])
 print(normalizeRows(x))

[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]]


### 1.5 广播和softmax函数

In [10]:
def softmax(x):
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp,axis=1, keepdims=True)
    x = x_exp / x_sum
    return x
    

In [11]:
x = np.array([[9, 2, 5, 0, 8],[7, 5, 0, 0, 0]])
print(softmax(x))

[[7.20860803e-01 6.57339966e-04 1.32030262e-02 8.89612905e-05
  2.65189869e-01]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


## 2 向量化
### 2.1 实现L1和L2损失函数

In [12]:
def L1(y_hat, y):
    loss = np.sum(np.abs(y - y_hat))
    return loss

In [13]:
def L2(y_hat, y):
    loss = np.sum((y-y_hat)**2)
    return loss

In [14]:
# 测试上述两个损失函数
y_hat = np.array([0.9, 0.2, 0.1, 0.4, 0.9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = "+str(L1(y_hat, y)))
print("L2 = "+str(L2(y_hat, y)))

L1 = 1.1
L2 = 0.43
